numbers = {1,2, 3,4,5}
empty_set = set()
print(numbers)
print(empty_set)
numbers.add(6)
print(numbers)
numbers.remove(3)
print(numbers)
numbers.discard(4)
print(numbers)
numbers.pop()
print(numbers)
numbers.clear()
print(numbers)
numbers.add(1)
numbers.add(1)
print(numbers)
